config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :employees
  resources :locations
  resources :companies
  root to: 'companies#index'
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :company
  belongs_to :location
  has_many :employees_courses
  has_many :courses, through: :employees_courses
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    @employees = Employee.paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @employees = Employee.where(id: params[:id])
    @locations = Employee.all.where(id: params[:id])[0]
    @courses   = @employees[0].courses
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name, :hire_date, :title, :company_id, :location_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hire_date %><br>
    <%= f.text_field :hire_date %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.text_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.text_field :location_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="center">Company Employees</h2>
<%= render partial: 'shared/employees',
            locals: { employees: @employees, paginate: true } %>
<!-- <%= react_component('Employee', { employees: @employees }) %> -->
<div class="center">
  <%= link_to 'New Employee', new_employee_path, class: 'btn btn-default' %>
</div>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>
<div class="center"><h2><%= @employees[0].company.name %></h2></div>
<h3 class="center">Location: <%= @locations.name %></h3>
<h3>Employee</h3>
<%= render partial: 'shared/employees',
            locals: { employees: @employees, paginate: false } %>

<h3>Employee Courses</h3>
<%= render partial: 'shared/courses',
            locals: {   courses: @courses,   paginate: false } %>

<div class="center">
  <%= link_to 'Edit', edit_employee_path(@employee), class: 'btn btn-default' %>
  <%= link_to 'Back', employees_path, class: 'btn btn-default' %>
</div>