config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :employees
  resources :locations
  resources :companies
  root to: 'companies#index'
end

app/views/shared/_companies.html.erb
<section class="panel panel-default">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% companies.each do |company| %>
        <tr>
          <td><%= company.name %></td>
          <td><%= link_to 'Show', company %></td>
          <td><%= link_to 'Edit', edit_company_path(company) %></td>
          <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <div class="center">
    <% if paginate %>
      <%= will_paginate companies, renderer: BootstrapPagination::Rails %>
    <% end %>
  </div>
</section>

app/views/shared/_courses.html.erb
<section class="panel panel-default">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Max count</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% courses.each do |course| %>
        <tr>
          <td><%= course.name %></td>
          <td><%= course.max_count %></td>
          <td><%= link_to 'Show', course %></td>
          <td><%= link_to 'Edit', edit_course_path(course) %></td>
          <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <div class="center">
    <% if paginate %>
      <%= will_paginate courses, renderer: BootstrapPagination::Rails %>
    <% end %>
  </div>
</section>

app/views/shared/_employees.html.erb
<section class="panel panel-default">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Hire date</th>
        <th>Title</th>
        <th>Company</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% employees.each do |employee| %>
        <tr>
          <td><%= employee.name %></td>
          <td><%= employee.hire_date %></td>
          <td><%= employee.title %></td>
          <td><%= employee.company.name %></td>
          <td><%= link_to 'Show', employee %></td>
          <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
          <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <div class="center">
    <% if paginate %>
      <%= will_paginate employees, renderer: BootstrapPagination::Rails %>
    <% end %>
  </div>
</section>

app/views/shared/_locations.html.erb
<section class="panel panel-default">
  <table class="table">
    <thead>
      <tr>
        <th>City</th>
        <th>Company</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% locations.each do |location| %>
        <tr>
          <td><%= location.city %></td>
          <td><%= location.company.name %></td>
          <td><%= link_to 'Show', location %></td>
          <td><%= link_to 'Edit', edit_location_path(location) %></td>
          <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <div class="center">
    <% if paginate %>
      <%= will_paginate locations, renderer: BootstrapPagination::Rails %>
    <% end %>
  </div>
</section>