config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :employees
  resources :locations
  resources :companies
  root to: 'companies#index'
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :locations
  has_many :employees
  has_many :courses, through: :locations
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]


  def index
    @companies = Company.paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @companies = Company.where(id: params[:id])
    @locations = Location.all.where(company_id: @companies[0].id)
    @courses = Company.all.where(id: params[:id])[0].courses
                             .paginate(:page => params[:page], :per_page => 10)
    @employees = Employee.all.where(company_id: @companies[0].id)
                             .paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="center">Companies</h2>
<%= render partial: 'shared/companies',
            locals: { companies: @companies, paginate: true } %>
<div class="center">
  <%= link_to 'New Company', new_company_path, class: 'btn btn-default' %>
</div>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<div class="center"><h2><%= @companies[0].name %></h2></div>
<h3>Locations</h3>
<%= render partial: 'shared/locations',
            locals: { locations: @locations, paginate: false } %>
<h3>Current Employees</h3>
<%= render partial: 'shared/employees',
            locals: { employees: @employees, paginate: true } %>
<h3>Courses</h3>
<%= render partial: 'shared/courses',
            locals: {   courses: @courses,   paginate: true } %>
<div class="center">
  <%= link_to 'Edit', edit_company_path(@company), class: 'btn btn-default' %>
  <%= link_to 'Back', companies_path, class: 'btn btn-default' %>
</div>