config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :employees
  resources :locations
  resources :companies
  root to: 'companies#index'
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :company
  has_many :courses
  has_many :employees
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @locations = Location.where(id: params[:id])
    @courses   = @locations[0].courses.paginate(:page => params[:page], :per_page => 10)
    @employees = @locations[0].company.employees
                              .paginate(:page => params[:page], :per_page => 10)
    @companies = @locations[0].company.name
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:city, :company_id)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.text_field :company_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="center">Company Locations</h2>
<%= render partial: 'shared/locations',
            locals: { locations: @locations, paginate: true } %>
<div class="center">
  <%= link_to 'New Location', new_location_path, class: 'btn btn-default' %>
</div>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>
<div class="center"><h2><%= @companies %></h2></div>
<div class="center"><h2>Location: <%= @locations[0].city %></h2></div>

<h3>Courses</h3>
<%= render partial: 'shared/courses',
            locals: {   courses: @courses,   paginate: true } %>
<h3>Current Employees</h3>
<%= render partial: 'shared/employees',
            locals: { employees: @employees, paginate: true } %>
<div class="center">
  <%= link_to 'Edit', edit_location_path(@location), class: 'btn btn-default' %>
  <%= link_to 'Back', locations_path, class: 'btn btn-default' %>
</div>